#ifndef TARGET_ARDUINO
    #include <ctype.h>
#endif
#ifndef PLATFORM_CODE
    #define PLATFORM_CODE {0}
#endif

/* Smalltalk from Squeak4.6 with VMMaker 4.12.3 translated as C source on 25 June 2016 3:47:46 pm */
/* Automatically generated by
    SmartSyntaxPluginCodeGenerator VMMaker-dtl.319 uuid: d058d88c-331d-47ef-b178-fd26ca3de120
   from
    PNVM * SmallDEVS-PNVM-MM.11 uuid: f8490799-7849-4e98-9ee7-ad2070c4934d
 */




#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
/* Configuration options */
/* Platform specific definitions */

#include "pnvm_types.h"
#include "pnvm_utils.h"



/*** Constants ***/
